### ISSUE TITLE
Problem compiling examples

### ISSUE THREAD

**Issue by Coriolis2024** [lewisxhe/lewisxhe#1]
I'm having trouble compiling a few different example codes for the tbeam supreme. I've tried compiling for several different boards and I get the same error message. 
All of the errors seem to be related to the library UG82. I've followed all of the instructions. Am I doing something wrong? 
![Sensor error code](https://github.com/user-attachments/assets/b2639824-4efd-4bdf-99f4-8be8dbfc3d5b)
![Error code](https://github.com/user-attachments/assets/75e33de0-440a-47cd-a27f-d93dd60f346a)

**Comment by lewisxhe** [comment]
Please submit an issue in the relevant repository. This example can be compiled normally.
![image](https://github.com/user-attachments/assets/2e7df10a-257d-4c74-999b-e2271e13085e)

**Comment by Coriolis2024** [comment]
Very sorry. I am new to all of this.
